FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY infra/docker/requirements-mlflow.txt ./
RUN pip install --no-cache-dir -r requirements-mlflow.txt
COPY infra/mlflow/start.py ./infra/mlflow/start.py

CMD ["python", "infra/mlflow/start.py"]
