FROM apache/airflow:3.1.1-python3.12

RUN pip install --no-cache-dir \
    apache-airflow-providers-standard==1.9.1 \
    apache-airflow-providers-postgres==6.4.0 \
    minio==7.2.18 \
    psycopg[binary]==3.2.12 \
    psycopg2-binary==2.9.11 \
    python-dotenv==1.1.1 \
    redis==6.4.0 \
    pillow==12.3.0
